name: nomia-ci

on:
  pull_request:
  push:

jobs:
  nomia:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - run: python -m pip install --upgrade pip
      - run: python -m pip install .

      - name: Run Nomia check
        run: nomia check

      - name: Run Nomia audit
        run: nomia audit
